In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split

testData = pd.read_csv("test.csv")
testY = pd.read_csv("output.csv")
trainData = pd.read_csv("train.csv")

In [10]:
testData = testData.append(testY, sort=False)
testData.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,36306,Male,80.0,0.0,0.0,Yes,Private,Urban,83.84,21.1,formerly smoked,NaN
1,61829,Female,74.0,0.0,1.0,Yes,Self-employed,Rural,179.50,26.0,formerly smoked,NaN
2,14152,Female,14.0,0.0,0.0,No,children,Rural,95.16,21.2,NaN,NaN
3,12997,Male,28.0,0.0,0.0,No,Private,Urban,94.76,23.4,NaN,NaN
4,40801,Female,63.0,0.0,0.0,Yes,Govt_job,Rural,83.57,27.6,never smoked,NaN